### ISSUE TITLE
XSSLint.configure not working

### ISSUE THREAD

**Issue by StarNeit** [jenseng/xsslint#2]
XSSLint.configure({
  "jqueryObject.identifier": /^\$/,
  "safeString.function":     "htmlEscape"
});

It has got error, and also not working safeString.function.
I would like you to support some guide!!

**Comment by jenseng** [comment]
What is the exact error you are seeing?

I think the code above and the example in the README are wrong, it should instead be:

```
XSSLint.configure({
  "jqueryObject.identifier": [/^$/],
  "safeString.function": ["htmlEscape"]
});```

**Comment by StarNeit** [comment]
... possibly XSS-able `html()` call..

I have got always this warning message when I build gulp.
So I would like to know how to ignore html() for not showing above warning message.

**Comment by jenseng** [comment]
The sole purpose of xsslint is to identify possibly unsafe calls to `html()` and things like it. So if you really want it to ignore all `html()` calls, perhaps xsslint isn't what you want?

I'd be curious what the actual line in question is that's causing this warning, as you either: 1. have a legitimate XSS vulnerability or 2. you are doing something that xsslint doesn't recognize, in which case you can give it hints, e.g. given:

```
var myVar = "<b>this is actually ok</b>";
$("#foo").html(myVar);
```

xsslint looks at each expression in isolation; it doesn't know that myVar is safe. So you can either hint that it's safe by:

1. adding a comment above it, e.g. `// xsslint safeString.identifier myVar`, OR
2. globally whitelisting more identifiers/etc. via `XSSLint.configure` OR
3. reworking it into a single expression that xsslint can definitively say is safe, e.g. `$("#foo").html("<b>this is actually ok</b>");`
